### ISSUE TITLE
No Workflows from CronWorkflow

### ISSUE THREAD

**Issue by sdminonne** [AmadeusITGroup/workflow-controller#89]
Testcase here: https://gist.github.com/davidc-donorschoose/79bb22c203000d4ecea702618923e709

**Comment by sdminonne** [comment]
See [discussion](https://github.com/AmadeusITGroup/workflow-controller/issues/29#issuecomment-453247361)

**Comment by clamoriniere1A** [comment]
Hi @davidc-donorschoose 

I was able to reproduce your issue using your gist. 
I was also able to found the issue in the yaml content. 

```YAML
                  env:
                     # ....
                      - name: PRIMARY_DEV_CLUSTER
                        value: false
                   #   ...
```

the problem is the "boolean" as in the `value` that should be a string. Theoretically it should works like this, but Kubernetes api-machinery is a complex piece of code, it converts the yaml input into json before decoding the content into the golang struct, that is why the input value is seen as a "boolean" by the decoder, but the field in the golang struct is a "string".

To avoid this issue, you need to force the type in the yaml file.

```YAML
                  env:
                     # ....
                      - name: PRIMARY_DEV_CLUSTER
                        value: "false"
                   #   ...
```

I validated that the workflow-controller is able to create the `workflow` with this change.

Let us know if you have any other issues, and thank for using and testing the `workflow-controller`
